//*********/ CONSTANTS *****************/
const colors = ['red', 'green', 'blue', 'purple']; //this holds the array for the possible choices
const flashColors = ['white', 'yellow', 'cyan', 'black'];

//*********/ STATE VARIABLES ***********/
let results; //this will be the variable for comparing if the userWonLevel, and 
// what level they are on, or if they lost and the game resets to level one
let delay; //this variable will control the intervals between the lights flashing during 
// a level, and before the start of the next level. Also sets no time limit for the user
let playerButtonCount; //this compares each player click to the random sequence generated by
// the computer.
let compTurn; //this stops the user from being able to interact with the page while the
// computerPattern plays as well as initiates the turn.
let pattern = [];  // Array that holds Simon's pattern
let level;

//*********/ Event Listeners ***********/
document.querySelector('.colorBtns').addEventListener('click', clickedButtons);
document.querySelector('#startBtn').addEventListener('click', startGame);
document.querySelector('#playAgainBtn').addEventListener('click', playAgain);

// ******function********* //
// This function sets up the initial conditions for a new game of Simon Says
function startGame() {
  level = 0;
  delay = 500;
  compTurn = true;
  pattern = [];
  computerTurn();
  // let interval = setInterval(computerTurn, 2000);
  // playerTurn();
  // clickedButtons();
  // renderResults();
};

function getRandomColor() {
  // 0 .. 3
  return Math.floor(Math.random() * 4);
}

// rename this to verbNoun
function computerTurn() {
  // set color pattern for level 1
  level++;
  document.querySelector('#levelBtn').innerText = level;
  pattern.push(getRandomColor());
  console.log(pattern);
  renderPattern(0);
  compTurn = false;
  playerButtonCount = 0;
}


// javascript loop through array with delay
// https://stackoverflow.com/a/30865640/18523110
function renderPattern(i) {
  // loop through pattern (Simons) array
  if (i < pattern.length) {
    //    flash the color
    blinkColor(pattern[i]);

    setTimeout(() => {
      i++;
      renderPattern(i);
    }, 350);
  }
};

function blinkColor(color) {
  console.log("Flash button: " + colors[color]);
  let button = document.querySelector('#' + colors[color]);
  button.style.backgroundColor = flashColors[color];
  setTimeout(() => {
    button.style.backgroundColor = '';
  }, 250);
};

function clickedButtons(evt) {
  if (compTurn === false) {
    let buttonColor = evt.target.id;    // purple, green, red, blue
    let colorIndex = colors.indexOf(buttonColor);
    console.log('colorIndex = ' + colorIndex);
    if (isIncorrect(colorIndex)) {
      // Fail the game you're a loser loser!!!
      // Call your loser function, which ends the game
      compTurn = true;
      console.log("your loser!");
    } else {
      playerButtonCount++;
      if (playerButtonCount === level) {
        compTurn = true;
        computerTurn();
      }
    }
    
  }
};

function isIncorrect(colorIndex) {
  if (colorIndex !== pattern[playerButtonCount]) {
    return true;
  }
  return false;
}

function playAgain() {
  startGame();
};

